"""schema_relaciones_e4

Revision ID: 7b6c4bd1030a
Revises: 
Create Date: 2026-04-21 07:03:45.019834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6c4bd1030a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_clientes_documento', table_name='clientes', postgresql_where='(documento IS NOT NULL)')
    op.create_unique_constraint(None, 'clientes', ['documento'])
    op.drop_index('ux_clientes_fidelizacion_telefono', table_name='clientes_fidelizacion')
    op.create_unique_constraint(None, 'clientes_fidelizacion', ['telefono_whatsapp'])
    op.drop_index('ux_productos_codigo_barras', table_name='productos', postgresql_where='(codigo_barras IS NOT NULL)')
    op.create_unique_constraint(None, 'productos', ['codigo_barras'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', type_='unique')
    op.create_index('ux_productos_codigo_barras', 'productos', ['codigo_barras'], unique=True, postgresql_where='(codigo_barras IS NOT NULL)')
    op.drop_constraint(None, 'clientes_fidelizacion', type_='unique')
    op.create_index('ux_clientes_fidelizacion_telefono', 'clientes_fidelizacion', ['telefono_whatsapp'], unique=True)
    op.drop_constraint(None, 'clientes', type_='unique')
    op.create_index('ux_clientes_documento', 'clientes', ['documento'], unique=True, postgresql_where='(documento IS NOT NULL)')
    # ### end Alembic commands ###
